version: '3'

services:
  app:
    image: chenzhaoyu94/chatgpt-web # 总是使用latest,更新时重新pull该tag镜像即可
    ports:
      - 3002:3002
    environment:
      # 二选一
      OPENAI_API_KEY: xxxx
      # 二选一
      OPENAI_ACCESS_TOKEN: yJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6Ik1UaEVOVUpHTkVNMVFURTRNMEZCTWpkQ05UZzVNRFUxUlRVd1FVSkRNRU13UmtGRVFrRXpSZyJ9.eyJodHRwczovL2FwaS5vcGVuYWkuY29tL3Byb2ZpbGUiOnsiZW1haWwiOiJjdGd3a28xNEBkdmF0b2suYXNpYSIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJnZW9pcF9jb3VudHJ5IjoiVVMifSwiaHR0cHM6Ly9hcGkub3BlbmFpLmNvbS9hdXRoIjp7InVzZXJfaWQiOiJ1c2VyLWt1aWZzOVp3R0ZqTzdhY1kyc3FIUVg0RiJ9LCJpc3MiOiJodHRwczovL2F1dGgwLm9wZW5haS5jb20vIiwic3ViIjoiYXV0aDB8NjM4ZTFjNzI0MjE5NWM5MWE3NmUyOGRhIiwiYXVkIjpbImh0dHBzOi8vYXBpLm9wZW5haS5jb20vdjEiLCJodHRwczovL29wZW5haS5vcGVuYWkuYXV0aDBhcHAuY29tL3VzZXJpbmZvIl0sImlhdCI6MTY3NzkyMDE3OSwiZXhwIjoxNjc5MTI5Nzc5LCJhenAiOiJUZEpJY2JlMTZXb1RIdE45NW55eXdoNUU0eU9vNkl0RyIsInNjb3BlIjoib3BlbmlkIHByb2ZpbGUgZW1haWwgbW9kZWwucmVhZCBtb2RlbC5yZXF1ZXN0IG9yZ2FuaXphdGlvbi5yZWFkIG9mZmxpbmVfYWNjZXNzIn0.2iEDNBLxWw450DQUvVm4U2qTjPaSm4-BI_5GzZ2kRNaIJw0eqpJ5Mb6-Rbyjmr97rDnaQWtPCOn20YITbtEjB9ladUaW-JxiN-gHWg-mFlFCn3S7j1yYCpF0mkYCFdbeALZJaatpnYGuPZn1zjw2lYIsKR9CJSQhHmR07mhTFddwfQa_FKKJOGNBBxOn3AoBXcsMLzSIuzVrVlwGmZeJMctkQW9HUgj-bscvIpI1KrDTForPkU_PGK4blkXWW1A4wBvenpmQpe8jPX2cpoFEA7DfgG2v1AALo9FCkQZP9KzxlljLXwgL966SslqmjkoLUeJl71t89VfC37XzjTiF7Q
      # API接口地址，可选，设置 OPENAI_API_KEY 时可用
      OPENAI_API_BASE_URL: xxxx
      # 反向代理，可选
      API_REVERSE_PROXY: xxx
      # 超时，单位毫秒，可选
      TIMEOUT_MS: 60000
      # Socks代理，可选，和 SOCKS_PROXY_PORT 一起时生效
      SOCKS_PROXY_HOST: xxxx
      # Socks代理端口，可选，和 SOCKS_PROXY_HOST 一起时生效
      SOCKS_PROXY_PORT: xxxx
  nginx:
    build: nginx
    image: chatgpt/nginx
    ports:
      - '80:80'
    expose:
      - '80'
    volumes:
      - ./nginx/html/:/etc/nginx/html/
    links:
      - app
